[package]
name = "poe-dat-converter"
version = "0.1.0"
authors = ["jlmcmchl <jlmcmchl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob="0.3.0"
nom="5.1.2"
lazy_static="1.4.0"
byteorder="1.3.4"